use hebrew_accents::{
    Accent, AccentCategory, HebrewAccent, PoetryAccent, ProseAccent, PseudoAccent,
};

#[test]
fn testing_hebrew_prose_accent_categories() {
    // Disjunctives
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Silluq).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Atnach).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Segolta).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Shalshelet).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::ZaqephQatan).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::ZaqephGadol).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Revia).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Tiphcha).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Zarqa).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Pashta).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Yetiv).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Tevir).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Geresh).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Gershayim).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Pazer).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::PazerGadol).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::TelishaGedolah).category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Legarmeh).category(),
        Some(AccentCategory::Disjunctive)
    );
    // Conjunctives
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Munach).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Mahpakh).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Merkha).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::MerkhaKephulah).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Darga).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Azla).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::TelishaQetannah).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Galgal).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Mayela).category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        HebrewAccent::Prose(ProseAccent::Meteg).category(),
        Some(AccentCategory::Conjunctive)
    );
}

#[test]
fn testing_prose_accent_categories() {
    // Disjunctives
    assert_eq!(
        ProseAccent::Silluq.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Atnach.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Segolta.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Shalshelet.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::ZaqephQatan.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::ZaqephGadol.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Revia.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Tiphcha.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Zarqa.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Pashta.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Yetiv.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Tevir.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Geresh.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Gershayim.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Pazer.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::PazerGadol.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::TelishaGedolah.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        ProseAccent::Legarmeh.category(),
        Some(AccentCategory::Disjunctive)
    );
    // Conjunctives
    assert_eq!(
        ProseAccent::Munach.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Mahpakh.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Merkha.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::MerkhaKephulah.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Darga.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Azla.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::TelishaQetannah.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Galgal.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Mayela.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        ProseAccent::Meteg.category(),
        Some(AccentCategory::Conjunctive)
    );
}

#[test]
fn testing_poetry_accent_categories() {
    // Disjunctives
    assert_eq!(
        PoetryAccent::Silluq.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::OlehWeYored.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::Atnach.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::ReviaGadol.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::ReviaMugrash.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::ShalsheletGadol.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::Tsinnor.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::ReviaQaton.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::Dechi.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::Pazer.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::MehuppakhLegarmeh.category(),
        Some(AccentCategory::Disjunctive)
    );
    assert_eq!(
        PoetryAccent::AzlaLegarmeh.category(),
        Some(AccentCategory::Disjunctive)
    );
    // Conjunctives
    assert_eq!(
        PoetryAccent::Munach.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Merkha.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Illuy.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Tarcha.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Galgal.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Mehuppakh.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Azla.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::ShalsheletQetannah.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::TsinnoritMerkha.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::TsinnoritMahpakh.category(),
        Some(AccentCategory::Conjunctive)
    );
    assert_eq!(
        PoetryAccent::Meteg.category(),
        Some(AccentCategory::Conjunctive)
    );
}

#[test]
fn testing_pseudo_accent_categories() {
    assert_eq!(
        HebrewAccent::Pseudo(PseudoAccent::SophPasuq).category(),
        None
    );
    assert_eq!(HebrewAccent::Pseudo(PseudoAccent::Maqqeph).category(), None);
    assert_eq!(HebrewAccent::Pseudo(PseudoAccent::Paseq).category(), None);

    assert_eq!(PseudoAccent::SophPasuq.category(), None);
    assert_eq!(PseudoAccent::Maqqeph.category(), None);
    assert_eq!(PseudoAccent::Paseq.category(), None);
}
