// pub const ETNAHTA:char = '\u{0591}'; // UTF-8 Code-point for ETNAHTA
// pub const SEGOL:char = '\u{0592}'; // UTF-8 Code-point for SEGOL
// pub const SHALSHELET:char = '\u{0593}'; // UTF-8 Code-point for SHALSHELET
// pub const ZAQEF_QATAN:char = '\u{0594}'; // UTF-8 Code-point for ZAQEF QATAN
// pub const ZAQEF_GADOL:char = '\u{0595}'; // UTF-8 Code-point for ZAQEF GADOL
// pub const TIPEHA:char = '\u{0596}'; // UTF-8 Code-point for TIPEHA
pub const REVIA: char = '\u{0597}'; // UTF-8 Code-point for REVIA
pub const ZARQA: char = '\u{0598}'; // UTF-8 Code-point for ZARQA
                                    // pub const PASHTA:char = '\u{0599}'; // UTF-8 Code-point for PASHTA
                                    // pub const YETIV:char = '\u{059A}'; // UTF-8 Code-point for YETIV
                                    // pub const TEVIR:char = '\u{059B}'; // UTF-8 Code-point for TEVIR
                                    // pub const GERESH:char = '\u{059C}'; // UTF-8 Code-point for GERESH
                                    // pub const GERESH_MUQDAM:char = '\u{059D}'; // UTF-8 Code-point for GERESH MUQDAM
                                    // pub const GERSHAYIM:char = '\u{059E}'; // UTF-8 Code-point for GERSHAYIM
                                    // pub const QARNEY_PARA:char = '\u{059F}'; // UTF-8 Code-point for QARNEY PARA
                                    // pub const TELISHA_GEDOLA:char = '\u{05A0}'; // UTF-8 Code-point for TELISHA GEDOLA
                                    // pub const PAZER:char = '\u{05A1}'; // UTF-8 Code-point for PAZER
                                    // pub const ATNAH_HAFUKH:char = '\u{05A2}'; // UTF-8 Code-point for ATNAH HAFUKH
                                    // pub const MUNAH:char = '\u{05A3}'; // UTF-8 Code-point for MUNAH
pub const MAHPAKH: char = '\u{05A4}'; // UTF-8 Code-point for MAHAPAKH
pub const MERKHA: char = '\u{05A5}'; // UTF-8 Code-point for MERKHA
                                     // pub const MERKHA_KEFULA:char = '\u{05A6}'; // UTF-8 Code-point for MERKHA KEFULA
                                     // pub const DARGA:char = '\u{05A7}'; // UTF-8 Code-point for DARGA
                                     // pub const QADMA:char = '\u{05A8}'; // UTF-8 Code-point for QADMA
                                     // pub const TELISHA_QETANA:char = '\u{05A9}'; // UTF-8 Code-point for TELISHA QETANA
                                     // pub const YERAH_BEN_YOMO:char = '\u{05AA}'; // UTF-8 Code-point for YERAH BEN YOMO
pub const OLE: char = '\u{05AB}'; // UTF-8 Code-point for OLE
                                  // pub const ILUY:char = '\u{05AC}'; // UTF-8 Code-point for ILUY
                                  // pub const DEHI:char = '\u{05AD}'; // UTF-8 Code-point for DEHI
                                  // pub const ZINOR:char = '\u{05AE}'; // UTF-8 Code-point for ZINOR
                                  // pub const MASORA_CIRCLE:char = '\u{05AF}'; // UTF-8 Code-point for HEBREW MARK MASORA CIRCLE
                                  // pub const SHEVA:char = '\u{05B0}'; // UTF-8 Code-point for HEBREW POINT SHEVA
                                  // pub const HATAF_SEGOL:char = '\u{05B1}'; // UTF-8 Code-point for HEBREW POINT HATAF SEGOL
                                  // pub const HATAF_PATAH:char = '\u{05B2}'; // UTF-8 Code-point for HEBREW POINT HATAF PATAH
                                  // pub const HATAF_QAMATS:char = '\u{05B3}'; // UTF-8 Code-point for HEBREW POINT HATAF QAMATS
                                  // pub const HIRIQ:char = '\u{05B4}'; // UTF-8 Code-point for HEBREW POINT HIRIQ
                                  // pub const TSERE:char = '\u{05B5}'; // UTF-8 Code-point for HEBREW POINT TSERE
                                  // pub const SEGOL:char = '\u{05B6}'; // UTF-8 Code-point for HEBREW POINT SEGOL
                                  // pub const PATAH:char = '\u{05B7}'; // UTF-8 Code-point for HEBREW POINT PATAH
                                  // pub const QAMATS:char = '\u{05B8}'; // UTF-8 Code-point for HEBREW POINT QAMATS
                                  // pub const HOLAM:char = '\u{05B9}'; // UTF-8 Code-point for HEBREW POINT HOLAM
                                  // pub const HOLAM_HASER:char = '\u{05BA}'; // UTF-8 Code-point for HEBREW POINT HOLAM HASER FOR VAV
                                  // pub const QUBUTS:char = '\u{05BB}'; // UTF-8 Code-point for HEBREW POINT QUBUTS
                                  // pub const DAGESH:char = '\u{05BC}'; // UTF-8 Code-point for HEBREW POINT DAGESH OR MAPIQ
                                  // pub const MAPIQ:char = '\u{05BC}'; // UTF-8 Code-point for HEBREW POINT DAGESH OR MAPIQ
                                  // pub const METEG:char = '\u{05BD}'; // UTF-8 Code-point for HEBREW POINT METEG
pub const MAQAF: char = '\u{05BE}'; // UTF-8 Code-point for HEBREW PUNCTUATION MAQAF
                                    // pub const RAFE:char = '\u{05BF}'; // UTF-8 Code-point for HEBREW POINT RAFE
pub const PASEQ: char = '\u{05C0}'; // UTF-8 Code-point for HEBREW PUNCTUATION PASEQ
                                    // pub const SHIN_DOT:char = '\u{05C1}'; // UTF-8 Code-point for HEBREW POINT SHIN_DOT
                                    // pub const SIN_DOT:char = '\u{05C2}'; // UTF-8 Code-point for HEBREW POINT SIN_DOT
                                    // pub const SOF_PASUQ:char = '\u{05C3}'; // UTF-8 Code-point for HEBREW PUNCTUATION SOF PASUQ
                                    // pub const UPPER_DOT:char = '\u{05C4}'; // UTF-8 Code-point for UPPER_DOT
                                    // pub const LOWER_DOT:char = '\u{05C5}'; // UTF-8 Code-point for HEBREW MARK LOWER_DOT
                                    // pub const NUN_HAFUKHA:char = '\u{05C6}'; // UTF-8 Code-point for HEBREW PUNCTUATION NUN HAFUKHA
                                    // pub const QAMATS_QATAN:char = '\u{05C7}'; // UTF-8 Code-point for HEBREW POINT QAMATS QATAN
                                    // pub const ALEF:char = '\u{05D0}'; // UTF-8 Code-point for HEBREW LETTER ALEF
                                    // pub const BET:char = '\u{05D1}'; // UTF-8 Code-point for HEBREW LETTER BET
                                    // pub const GIMEL:char = '\u{05D2}'; // UTF-8 Code-point for HEBREW LETTER GIMEL
                                    // pub const DALET:char = '\u{05D3}'; // UTF-8 Code-point for HEBREW LETTER DALET
                                    // pub const HE:char = '\u{05D4}'; // UTF-8 Code-point for HEBREW LETTER HE
                                    // pub const VAV:char = '\u{05D5}'; // UTF-8 Code-point for HEBREW LETTER VAV
                                    // pub const ZAYIN:char = '\u{05D6}'; // UTF-8 Code-point for HEBREW LETTER ZAYIN
                                    // pub const HET:char = '\u{05D7}'; // UTF-8 Code-point for HEBREW LETTER HET
                                    // pub const TET:char = '\u{05D8}'; // UTF-8 Code-point for HEBREW LETTER TET
                                    // pub const YOD:char = '\u{05D9}'; // UTF-8 Code-point for HEBREW LETTER YOD
                                    // pub const FINAL_KAF:char = '\u{05DA}'; // UTF-8 Code-point for HEBREW LETTER FINAL_KAF
                                    // pub const KAF:char = '\u{05DB}'; // UTF-8 Code-point for HEBREW LETTER KAF
                                    // pub const LAMED:char = '\u{05DC}'; // UTF-8 Code-point for HEBREW LETTER LAMED
                                    // pub const FINAL_MEM:char = '\u{05DD}'; // UTF-8 Code-point for HEBREW LETTER FINAL_MEM
                                    // pub const MEM:char = '\u{05DE}'; // UTF-8 Code-point for HEBREW LETTER MEM
                                    // pub const FINAL_NUN:char = '\u{05DF}'; // UTF-8 Code-point for HEBREW LETTER FINAL_NUN
                                    // pub const NUN:char = '\u{05E0}'; // UTF-8 Code-point for HEBREW LETTER NUN
                                    // pub const SAMEKH:char = '\u{05E1}'; // UTF-8 Code-point for HEBREW LETTER SAMEKH
                                    // pub const AYIN:char = '\u{05E2}'; // UTF-8 Code-point for HEBREW LETTER AYIN
                                    // pub const FINAL_PE:char = '\u{05E3}'; // UTF-8 Code-point for HEBREW LETTER FINAL_PE
                                    // pub const PE:char = '\u{05E4}'; // UTF-8 Code-point for HEBREW LETTER PE
                                    // pub const FINAL_TSADI:char = '\u{05E5}'; // UTF-8 Code-point for HEBREW LETTER FINAL_TSADI
                                    // pub const TSADI:char = '\u{05E6}'; // UTF-8 Code-point for HEBREW LETTER TSADI
                                    // pub const QOF:char = '\u{05E7}'; // UTF-8 Code-point for HEBREW LETTER QOF
                                    // pub const RESH:char = '\u{05E8}'; // UTF-8 Code-point for HEBREW LETTER RESH
                                    // pub const SHIN:char = '\u{05E9}'; // UTF-8 Code-point for HEBREW LETTER SHIN
                                    // pub const TAV:char = '\u{05EA}'; // UTF-8 Code-point for HEBREW LETTER TAV
                                    // pub const YODTRIANGLE:char = '\u{05EF}'; // UTF-8 Code-point for HEBREW YOD TRIANGLE
                                    // pub const YIDDISH_DOUBLE_VAV:char = '\u{05F0}'; // UTF-8 Code-point for HEBREW LIGATURE YIDDISH_DOUBLE_VAV
                                    // pub const YIDDISH_VAV_YOD:char = '\u{05F1}'; // UTF-8 Code-point for HEBREW LIGATURE YIDDISH VAV YOD
                                    // pub const YIDDISH_DOUBLE_YOD:char = '\u{05F2}'; // UTF-8 Code-point for HEBREW LIGATURE YIDDISH_DOUBLE_YOD
                                    // pub const GERESH:char = '\u{05F3}'; // UTF-8 Code-point for HEBREW PUNCTUATION GERESH
                                    // pub const GERSHAYIM:char = '\u{05F4}'; // UTF-8 Code-point for HEBREW PUNCTUATION GERSHAYIM
                                    // pub const YOD_WITH_HIRIQ:char = '\u{FB1D}'; // UTF-8 Code-point for HEBREW LETTER YOD_WITH_HIRIQ
                                    // pub const JUDEO_SPANISH_VARIKA:char = '\u{FB1E}'; // UTF-8 Code-point for HEBREW POINT JUDEO-SPANISH VARIKA
                                    // pub const YOD_YOD_PATAH:char = '\u{FB1F}'; // UTF-8 Code-point for HEBREW LIGATURE YIDDISH YOD YOD PATAH
                                    // pub const ALTERNATIVE_AYIN:char = '\u{FB20}'; // UTF-8 Code-point for HEBREW LETTER ALTERNATIVE AYIN
                                    // pub const WIDE_ALEF:char = '\u{FB21}'; // UTF-8 Code-point for HEBREW LETTER WIDE_ALEF
                                    // pub const WIDE_DALET:char = '\u{FB22}'; // UTF-8 Code-point for HEBREW LETTER WIDE_DALET
                                    // pub const WIDE_HE:char = '\u{FB23}'; // UTF-8 Code-point for HEBREW LETTER WIDE_HE
                                    // pub const WIDE_KAF:char = '\u{FB24}'; // UTF-8 Code-point for HEBREW LETTER WIDE_KAF
                                    // pub const WIDE_LAMED:char = '\u{FB25}'; // UTF-8 Code-point for HEBREW LETTER WIDE_LAMED
                                    // pub const WIDE_FINAL_MEM:char = '\u{FB26}'; // UTF-8 Code-point for HEBREW LETTER WIDE_FINAL_MEM
                                    // pub const WIDE_RESH:char = '\u{FB27}'; // UTF-8 Code-point for HEBREW LETTER WIDE_RESH
                                    // pub const WIDE_TAV:char = '\u{FB28}'; // UTF-8 Code-point for HEBREW LETTER WIDE TAV
                                    // pub const ALTERNATIVE_PLUS_SIGN:char = '\u{FB29}'; // UTF-8 Code-point for HEBREW LETTER ALTERNATIVE PLUS SIGN
                                    // pub const SHIN_WITH_SHIN_DOT:char = '\u{FB2A}'; // UTF-8 Code-point for HEBREW LETTER SHIN_WITH_SHIN_DOT
                                    // pub const SHIN_WITH_SIN_DOT:char = '\u{FB2B}'; // UTF-8 Code-point for HEBREW LETTER SHIN_WITH_SIN_DOT
                                    // pub const SHIN_WITH_DAGESH_AND_SHIN_DOT:char = '\u{FB2C}'; // UTF-8 Code-point for HEBREW LETTER SHIN_WITH_DAGESH_AND_SHIN_DOT
                                    // pub const SHIN_WITH_DAGESH_AND_SIN_DOT:char = '\u{FB2D}'; // UTF-8 Code-point for HEBREW LETTER SHIN_WITH_DAGESH_AND_SIN_DOT
                                    // pub const ALEF_WITH_PATAH:char = '\u{FB2E}'; // UTF-8 Code-point for HEBREW LETTER ALEF_WITH_PATAH
                                    // pub const ALEF_WITH_QAMATS:char = '\u{FB2F}'; // UTF-8 Code-point for HEBREW LETTER ALEF_WITH_QAMATS
                                    // pub const ALEF_WITH_MAPIQ:char = '\u{FB30}'; // UTF-8 Code-point for HEBREW LETTER ALEF_WITH_MAPIQ
                                    // pub const BET_WITH_DAGESH:char = '\u{FB31}'; // UTF-8 Code-point for HEBREW LETTER BET_WITH_DAGESH
                                    // pub const GIMEL_WITH_DAGESH:char = '\u{FB32}'; // UTF-8 Code-point for HEBREW LETTER GIMEL_WITH_DAGESH
                                    // pub const DALET_WITH_DAGESH:char = '\u{FB33}'; // UTF-8 Code-point for HEBREW LETTER DALET_WITH_DAGESH
                                    // pub const HE_WITH_MAPIQ:char = '\u{FB34}'; // UTF-8 Code-point for HEBREW LETTER HE_WITH_MAPIQ
                                    // pub const VAV_WITH_DAGESH:char = '\u{FB35}'; // UTF-8 Code-point for HEBREW LETTER VAV_WITH_DAGESH
                                    // pub const ZAYIN_WITH_DAGESH:char = '\u{FB36}'; // UTF-8 Code-point for HEBREW LETTER ZAYIN_WITH_DAGESH
                                    // pub const TET_WITH_DAGESH:char = '\u{FB38}'; // UTF-8 Code-point for HEBREW LETTER TET_WITH_DAGESH
                                    // pub const YOD_WITH_DAGESH:char = '\u{FB39}'; // UTF-8 Code-point for HEBREW LETTER YOD_WITH_DAGESH
                                    // pub const FINAL_KAF_WITH_DAGESH:char = '\u{FB3A}'; // UTF-8 Code-point for HEBREW LETTER FINAL_KAF_WITH_DAGESH
                                    // pub const KAF_WITH_DAGESH:char = '\u{FB3B}'; // UTF-8 Code-point for HEBREW LETTER KAF_WITH_DAGESH
                                    // pub const LAMED_WITH_DAGESH:char = '\u{FB3C}'; // UTF-8 Code-point for HEBREW LETTER LAMED_WITH_DAGESH
                                    // pub const MEM_WITH_DAGESH:char = '\u{FB3E}'; // UTF-8 Code-point for HEBREW LETTER MEM_WITH_DAGESH
                                    // pub const NUN_WITH_DAGESH:char = '\u{FB40}'; // UTF-8 Code-point for HEBREW LETTER NUN_WITH_DAGESH
                                    // pub const SAMEKH_WITH_DAGESH:char = '\u{FB41}'; // UTF-8 Code-point for HEBREW LETTER SAMEKH_WITH_DAGESH
                                    // pub const FINAL_PE_WITH_DAGESH:char = '\u{FB43}'; // UTF-8 Code-point for HEBREW LETTER FINAL_PE_WITH_DAGESH
                                    // pub const PE_WITH_DAGESH:char = '\u{FB44}'; // UTF-8 Code-point for HEBREW LETTER PE_WITH_DAGESH
                                    // pub const TSADI_WITH_DAGESH:char = '\u{FB46}'; // UTF-8 Code-point for HEBREW LETTER TSADI_WITH_DAGESH
                                    // pub const QOF_WITH_DAGESH:char = '\u{FB47}'; // UTF-8 Code-point for HEBREW LETTER QOF_WITH_DAGESH
                                    // pub const RESH_WITH_DAGESH:char = '\u{FB48}'; // UTF-8 Code-point for HEBREW LETTER RESH_WITH_DAGESH
                                    // pub const SHIN_WITH_DAGESH:char = '\u{FB49}'; // UTF-8 Code-point for HEBREW LETTER SHIN_WITH_DAGESH
                                    // pub const TAV_WITH_DAGESH:char = '\u{FB4A}'; // UTF-8 Code-point for HEBREW LETTER TAV_WITH_DAGESH
                                    // pub const VAV_WITH_HOLAM:char = '\u{FB4B}'; // UTF-8 Code-point for HEBREW LETTER VAV_WITH_HOLAM
                                    // pub const BET_WITH_RAFE:char = '\u{FB4C}'; // UTF-8 Code-point for HEBREW LETTER BET_WITH_RAFE
                                    // pub const KAF_WITH_RAFE:char = '\u{FB4D}'; // UTF-8 Code-point for HEBREW LETTER KAF_WITH_RAFE
                                    // pub const PE_WITH_RAFE:char = '\u{FB4E}'; // UTF-8 Code-point for HEBREW LETTER PE WITH RAFE
                                    // pub const ALEF_LAMED:char = '\u{FB4F}'; // UTF-8 Code-point for HEBREW LIGATURE ALEF LAMED
                                    // misc
pub const VERTICAL_LINE: char = '\u{007C}'; // UTF-8 Code-point for VERTICAL LINE
